// Writes src/generated/site-meta.js from src/pages.js so the runtime has titles/descriptions without importing the
// content files. Runs before `vite build` (package.json). Output is committed so `vite` dev works without a build.
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { SITE_PAGES, SITE_NAME, ALIASES, NOT_FOUND } from '../src/pages.js'
import { TREATMENT_PAGES } from '../src/content/treatments/index.js'
const ROOT = resolve(import.meta.dirname, '..')
mkdirSync(resolve(ROOT, 'src/generated'), { recursive: true })
const meta = SITE_PAGES.map(({ path, title, description }) => ({ path, title, description }))
const nf = { title: NOT_FOUND.title, description: NOT_FOUND.description, notFound: true }
writeFileSync(resolve(ROOT, 'src/generated/site-meta.js'), `// GENERATED by tools/gen-meta.mjs from src/pages.js — do not edit.\nexport const SITE_NAME = ${JSON.stringify(SITE_NAME)}\nexport const ALIASES = ${JSON.stringify(ALIASES)}\nexport const NOT_FOUND = ${JSON.stringify(nf)}\nexport const SITE_META = ${JSON.stringify(meta, null, 1)}\n`)
console.log(`gen-meta: ${meta.length} pages`)

// Search index, treatments part (2026-09-23): the content files are 42 KB and load per page, so the search overlay
// gets a digest instead — title, department, and the service names each page lists (items that have a title and a
// text), verbatim. Why-choose, journey, FAQ and featured blocks are skipped: they describe the clinic, not a service.
// Doctors and clinics are indexed at runtime from their data files (src/search/sources.js), which are small.
const SKIP = new Set(['whyChoose', 'journey', 'faq', 'featured', 'closing', 'conversation', 'form', 'hero', 'risksSafety', 'before'])
const GENERIC = /^(specialities under this roof|common questions|featured service|flagship)$/i
const flat = (t) => (Array.isArray(t) ? t.map((x) => (typeof x === 'string' ? x : x.text || '')).join(' ') : typeof t === 'string' ? t : '').replace(/\s+/g, ' ').trim()
function services(o, out) {
  if (Array.isArray(o)) { o.forEach((x) => services(x, out)); return }
  if (!o || typeof o !== 'object') return
  if (o.title && o.text) out.add(flat(o.title))
  if (o.head && typeof o.head.eyebrow === 'string') out.add(flat(o.head.eyebrow))
  if (typeof o.eyebrow === 'string' && o.items) out.add(flat(o.eyebrow))
  for (const [k, v] of Object.entries(o)) if (!SKIP.has(k)) services(v, out)
}
const treatments = Object.entries(TREATMENT_PAGES).filter(([, p]) => !p.alias).map(([slug, p]) => {
  const c = p.content; const kw = new Set(); services(c, kw)
  const list = [...kw].filter((k) => k && !GENERIC.test(k) && k !== c.title)
  return { id: slug, title: c.title, department: c.department || '', href: `/treatments/${slug}/`, services: list }
})
writeFileSync(resolve(ROOT, 'src/generated/search-treatments.js'), `// GENERATED by tools/gen-meta.mjs from src/content/treatments — do not edit.\nexport default ${JSON.stringify(treatments, null, 1)}\n`)
console.log(`gen-meta: search index, ${treatments.length} treatment pages`)
