// Writes src/generated/site-meta.js from src/pages.js so the runtime has titles/descriptions without importing the
// content files. Runs before `vite build` (package.json). Output is committed so `vite` dev works without a build.
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { SITE_PAGES, SITE_NAME, ALIASES, NOT_FOUND } from '../src/pages.js'
const ROOT = resolve(import.meta.dirname, '..')
mkdirSync(resolve(ROOT, 'src/generated'), { recursive: true })
const meta = SITE_PAGES.map(({ path, title, description }) => ({ path, title, description }))
const nf = { title: NOT_FOUND.title, description: NOT_FOUND.description, notFound: true }
writeFileSync(resolve(ROOT, 'src/generated/site-meta.js'), `// GENERATED by tools/gen-meta.mjs from src/pages.js — do not edit.\nexport const SITE_NAME = ${JSON.stringify(SITE_NAME)}\nexport const ALIASES = ${JSON.stringify(ALIASES)}\nexport const NOT_FOUND = ${JSON.stringify(nf)}\nexport const SITE_META = ${JSON.stringify(meta, null, 1)}\n`)
console.log(`gen-meta: ${meta.length} pages`)
