// Site-level content configuration. Swap media here, not in components.

// Hero video slot (src/components/VideoSlot.jsx). Set to null / '' to render the poster alone.
// PLACEHOLDER: a slow push-in on the hero photo, generated by tools/make-placeholder-video.py. Replace with the
// client's footage: the card panel is 497.7 × 654.4 at 1366 (0.761:1) — 3:4 footage at 1080 × 1440 loses 1.4 % of its
// width under object-fit: cover.
export const HERO_VIDEO_SRC = '/media/standin-pale.mp4'   // placeholder: CDC milestone clip (public domain), pale interior

// The design's hero photo: poster frame and the fallback when there is no video or it fails to load.
export const HERO_POSTER = '/assets/2_04c0f486.png'

// Footage treatment: 'flush' (Option A, matched backdrop, no visible edge) or 'card' (Option B, rounded panel + shadow).
// Overridable for mock-ups with ?videoStyle=card|flush.
export const HERO_VIDEO_STYLE = 'card'   // decided 2026-09-17 (design/video-options.md)
