// Site-level content configuration. Swap media here, not in components.

// Hero video slot (src/components/VideoSlot.jsx). Set to null / '' to render the poster alone.
// PLACEHOLDER: a slow push-in on the hero photo, generated by tools/make-placeholder-video.py. Replace with the
// client's footage: portrait 11:15 (the slot is 497.7 × 678.7 at 1366) — 3:4 shot at 1080 × 1440 crops 2 % off
// the height under object-fit: cover.
export const HERO_VIDEO_SRC = '/media/hero-placeholder.mp4'

// The design's hero photo: poster frame and the fallback when there is no video or it fails to load.
export const HERO_POSTER = '/assets/2_04c0f486.png'
