// Site-level content configuration. Swap media here, not in components.

// Hero video slot (src/components/VideoSlot.jsx). Set to null / '' to render the poster alone.
// PLACEHOLDER: a slow push-in on the hero photo, generated by tools/make-placeholder-video.py. Replace with the
// client's footage: the card panel is 497.7 × 654.4 at 1366 (0.761:1) — 3:4 footage at 1080 × 1440 loses 1.4 % of its
// width under object-fit: cover.
export const HERO_VIDEO_SRC = '/media/standin-landscape.mp4'   // placeholder: CDC milestone clip (public domain), 16:9
// Phones (<768) get this lighter encode. Both re-encoded 2026-09-24 (H.264, no audio, 25 fps, faststart):
// 1280×720 ≈650 kbps 798 KB (was 1.30 MB at 1.06 Mbps) and 640×360 ≈220 kbps 270 KB. Client footage: same two outputs.
export const HERO_VIDEO_SRC_MOBILE = '/media/standin-landscape-m.mp4'

// The design's hero photo: poster frame and the fallback when there is no video or it fails to load.
export const HERO_POSTER = '/media/hero-poster-landscape.jpg'   // landscape poster (first frame). The design's portrait photo (/assets/2_04c0f486.png + mask) is kept on disk, unused since hero concept B

// Footage treatment: 'flush' (Option A, matched backdrop, no visible edge) or 'card' (Option B, rounded panel + shadow).
// Overridable for mock-ups with ?videoStyle=card|flush.
export const HERO_VIDEO_STYLE = 'full'   // round 3: full-width 16:9 video (Shelf hero). 'film' (concept B card), 'card' and 'flush' remain available

// ---- forms (decided 2026-09-17): every form posts to ONE Google Apps Script web app, which appends a row to a Google
// Sheet and sends an email notification. Replace the placeholder with the client's deployed web-app URL
// (https://script.google.com/macros/s/…/exec). While it says PLACEHOLDER, submissions are simulated (forms/submit.js).
export const FORM_ENDPOINT = 'https://script.google.com/macros/s/PLACEHOLDER/exec'
// Privacy notice linked from the consent line on every form. The page does not exist yet — client to supply the text.
export const PRIVACY_URL = '/privacy-policy.html'   // interim standalone page (public/privacy-policy.html) until the client's policy text arrives


// Site-wide (2026-09-18): canonical origin for the sitemap, canonical links and Open Graph; Google Tag Manager
// container id — empty until the client supplies one (analytics.js keeps events in window.__petalsEvents meanwhile).
export const SITE_URL = 'https://www.petalshealth.in'
export const GTM_ID = ''

// Staging (2026-09-21): `npm run build:staging` sets VITE_STAGING=1. On staging every page is noindex, robots.txt
// disallows all, there is no sitemap, forms can only reach the simulated placeholder endpoint (the ?leadEndpoint=
// test hook is ignored), analytics never loads, and a preview ribbon shows. Production builds ignore all of this.
// SXO lead-capture agent (design/round2-report.md §6). Timing is configuration: first appearance after delayMs, OR
// at scrollPct of the page, OR on exit intent — whichever first. repeatMs: null = never re-show in a session once
// dismissed or completed (the client's "every 20 seconds" would be repeatMs: 20000 — not built until asked).
export const SXO = { enabled: true, firstAppearance: { delayMs: 30000, scrollPct: 50, exitIntent: true }, repeatMs: null, dismissal: 'session' }

export const STAGING = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env.VITE_STAGING === '1' : false
